all:
  hosts:
    node1:
      ansible_host: 192.168.56.111
      ip: 192.168.56.111
      access_ip: 192.168.56.111
    node2:
      ansible_host: 192.168.56.112
      ip: 192.168.56.112
      access_ip: 192.168.56.112
    node3:
      ansible_host: 192.168.56.113
      ip: 192.168.56.113
      access_ip: 192.168.56.113
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
